### ISSUE TITLE
TOC for SDK reference is missing for Microsoft Teams developer documentation 

### ISSUE THREAD

**Issue by Wajeed-msft** [OfficeDev/msteams-client-docs-ref-typescript#39]
We no longer see the TOC for SDK reference for [Microsoft Teams Documentation](https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest).  Could you please help to fix this?

![image](https://user-images.githubusercontent.com/31851992/108673271-697eb880-7509-11eb-91b3-d632385578f8.png)

**Comment by erikadoyle** [comment]
Closing as this issue no longer repros.
